site_name: jfx's notes
site_description: My public notes
# site_url: https://mike.bailey.net.au/notes
site_author: Thomas

# Repository
repo_name: itsjfx/notes
repo_url: https://github.com/itsjfx/notes
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/master/docs/

# Copyright
copyright: Copyright &copy; 2022 - 2023 Thomas
theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/customization/?h=override#setup-and-theme-structure
  custom_dir: overrides
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    - content.action.view
  icon:
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    edit: material/pencil
    view: material/eye

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
